name: 'notebook'

services:
  nginx:
    container_name: notebook_nginx
    image: nginx:latest
    volumes:
      - ./:/var/www/notebook
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '8876:80'
    depends_on:
      - app

  app:
    container_name: notebook_app
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/notebook
    depends_on:
      - mysql

  mysql:
    container_name: notebook_mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_DATABASE: notebook_db
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - ./tmp/db:/var/lib/mysql